### PR TITLE
Modernize our project

### PR DESCRIPTION
**Pull request by rtlanceroad**
I joined the project in 2014, now is 2017, so, at least, the year is from 2014.

### CODE REVIEW

**Comment by kori** [comment]
#6c37 was created in January 05, 2015, so maybe 2015-2017?

**Comment by DanielFGray** [comment]
this is totally unnecessary.  you don't need a date range, you can just state "this is when i started these things" and your "copyright" is carried over to the present date

**Comment by rtlanceroad** [comment]
@DanielFGray Yeah, I know this is unnecessary, I just want to see, maybe someday in the future, you look back, then you find 'wow, there are 10 years'(maybe) contributing' then you get a sense of proud.

**Comment by kori** [comment]
LGTM, Merging

**Pull request merged**
